# Generated by Django 3.0.5 on 2021-05-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collatio', '0006_auto_20210519_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detailPageLink',
        ),
    ]
