# Generated by Django 3.0.5 on 2021-05-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collatio', '0007_remove_product_detailpagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
