# Generated by Django 3.0.5 on 2021-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collatio', '0008_auto_20210526_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
