# Generated by Django 3.0.5 on 2021-05-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collatio', '0009_auto_20210529_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
