# Generated by Django 3.0.5 on 2021-05-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collatio', '0010_auto_20210529_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bestLink',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
